name: "finance staging"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

env:
  CODENAME: tranvien98/finance
  SERVICE: finance
  NAMESPACE: dev-software
  TAG: ${{ github.run_id }}
  STAGE: staging
  SERVICE_PORT: 3000

jobs:
  install-build-and-push-to-k8s:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Login to K8S
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > /tmp/kubeconfig
          echo "KUBECONFIG=/tmp/kubeconfig" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ env.CODENAME }}/${{ env.STAGE }}/${{ env.SERVICE }}:latest,ghcr.io/${{ env.CODENAME }}/${{ env.STAGE }}/${{ env.SERVICE }}:${{ env.TAG }}
          cache-from: type=registry,ref=ghcr.io/${{ env.CODENAME }}/${{ env.STAGE }}/${{ env.SERVICE }}:latest
          cache-to: type=inline

      - name: Render Deployment YAML
        uses: nowactions/envsubst@v1
        with:
          input: ./k8s/deployment.yaml
          output: ./k8s/gen.deployment.yaml

      - name: Check Deployment Status
        run: |
          kubectl apply -f ./k8s/gen.deployment.yaml
          kubectl rollout status deployment/$SERVICE -n $NAMESPACE --watch
        env:
          SERVICE: ${{ env.SERVICE }}
          NAMESPACE: ${{ env.NAMESPACE }}
